services:
  - type: web
    name: zocker-freunde
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.21.0
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: DB_POOL_MAX
        value: "5"
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DISCORD_INVITE_URL
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_ADMIN_IDS
        sync: false
